# FILE: docker-compose.yml (Simplified for Host Ollama setup)

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Mount uploads volume for persistent storage
      - uploads_data:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rag_db
      # For accessing Ollama on the host machine
      - OLLAMA_HOST_URL=http://host.docker.internal:11434
      - LLM_MODEL=tinyllama
      - NODE_ENV=production
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      - mongo
      - qdrant
    restart: unless-stopped
    # This helps to ensure host.docker.internal works on all platforms
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
  mongo_data:
  uploads_data:

# networks: # Define if needed
#   default: