# FILE: docker-compose.yml (Corrected Frontend Build Context)

services:
  frontend:
    build:
      # *** FIX: Set context to project root for frontend build ***
      context: .
      # *** FIX: Specify Dockerfile path relative to the new context ***
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build:
      context: . # Correctly set to root
      dockerfile: backend/Dockerfile # Correct path
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rag_db
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST_URL=http://host.docker.internal:11434
      - NODE_ENV=production
    depends_on:
      - mongo
      - qdrant
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
  mongo_data: