# FILE: docker-compose.yml (Corrected Build Context for Backend)

services:
  frontend:
    build:
      context: ./frontend # Context is the frontend dir
      dockerfile: Dockerfile # Dockerfile is inside ./frontend/
    ports:
      - "3000:80"
    restart: unless-stopped

  backend:
    build:
      # *** FIX: Set context to project root ***
      context: .
      # *** FIX: Specify the Dockerfile path relative to the context ***
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Mount from host's backend/uploads to container's /app/uploads
      - ./backend/uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rag_db
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST_URL=http://host.docker.internal:11434 # For Docker Desktop
      - NODE_ENV=production
    depends_on:
      - mongo
      - qdrant
    restart: unless-stopped
    extra_hosts: # Keep this for host.docker.internal resolution
      - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:6.0
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
  mongo_data: