# D:\rag-app\python\config\__init__.py
"""
Configuration package for the RAG application
"""

from .models import (
    LLM_MODEL_NAME,
    EMBEDDING_MODEL_NAME,
    DEFAULT_VECTOR_SIZE,
    QDRANT_HOST,
    QDRANT_PORT,
    DEFAULT_COLLECTION,
    OLLAMA_HOST_URL,
    OLLAMA_API_BASE,
    CONTEXT_RETRIEVAL_LIMIT,
    MAX_CONTEXT_CHAR_LIMIT,
    MAX_HISTORY_TOKENS,
    TEXT_CHUNK_SIZE,
    TEXT_CHUNK_OVERLAP,
    IMAGE_SAVE_DIR_RELATIVE,
    RENDERING_DPI,
    print_current_config,
    # Phase 2: Hybrid Retrieval
    ENABLE_KNOWLEDGE_GRAPH,
    RRF_K,
    VECTOR_WEIGHT,
    BM25_WEIGHT,
    GRAPH_WEIGHT,
    GRAPH_TRAVERSAL_DEPTH,
    INDICES_DIR,
)

__all__ = [
    'LLM_MODEL_NAME',
    'EMBEDDING_MODEL_NAME', 
    'DEFAULT_VECTOR_SIZE',
    'QDRANT_HOST',
    'QDRANT_PORT',
    'DEFAULT_COLLECTION',
    'OLLAMA_HOST_URL',
    'OLLAMA_API_BASE',
    'CONTEXT_RETRIEVAL_LIMIT',
    'MAX_CONTEXT_CHAR_LIMIT',
    'MAX_HISTORY_TOKENS',
    'TEXT_CHUNK_SIZE',
    'TEXT_CHUNK_OVERLAP',
    'IMAGE_SAVE_DIR_RELATIVE',
    'RENDERING_DPI',
    'print_current_config',
    # Phase 2
    'ENABLE_KNOWLEDGE_GRAPH',
    'RRF_K',
    'VECTOR_WEIGHT',
    'BM25_WEIGHT',
    'GRAPH_WEIGHT',
    'GRAPH_TRAVERSAL_DEPTH',
    'INDICES_DIR',
]
